-- RPZ configuration for PowerBlockade

-- Query logging is handled by dnsdist (edge) via dnstap, which includes the true client IP.

-- Combined blocklists RPZ file (generated by blocklist manager)
rpzFile("/etc/pdns-recursor/rpz/blocklist-combined.rpz", {
  policyName = "blocklist-combined",
  defpol = Policy.NXDOMAIN,
})

-- Whitelist (allow overrides)
rpzFile("/etc/pdns-recursor/rpz/whitelist.rpz", {
  policyName = "whitelist",
  defpol = Policy.PASSTHRU,
})
